var RPC = {
  C2S_Enter_Room : "room.roomHandler.enterRoom",
  C2S_Player_Rotate : "room.roomHandler.onPlayerRotate",
  C2S_Player_Attack : "room.roomHandler.onPlayerAttack",
  C2S_Player_SpeedUp : "room.roomHandler.onPlayerSpeedUp",
  C2S_Player_Hang : "room.roomHandler.onPlayerHang",
  C2S_Player_SwitchMove : "room.roomHandler.onPlayerSwitchMove",
  C2S_Enter_Lobby : "lobby.lobbyHandler.enterLobby",
  C2S_ShareToGetReviveStone : "lobby.lobbyHandler.shareToGetReviveStone",
  C2S_WatchAdToGetGold : "lobby.lobbyHandler.watchAdToGetGold",
  C2S_BuyBuff : "lobby.lobbyHandler.buyBuff",
  C2S_UseReviveStone : "lobby.lobbyHandler.useReviveStone",
  C2S_UploadBattleResult : "lobby.lobbyHandler.uploadBattleResult",
  C2S_UploadName : "lobby.lobbyHandler.uploadName",
  C2S_DailyPrize : "lobby.lobbyHandler.dailyPrize",
  C2S_ShopBuy : "lobby.lobbyHandler.shopBuy",
  C2S_GrowProp : "lobby.lobbyHandler.growProp",
  C2S_CostGold : "lobby.lobbyHandler.costGold",

  S2C_PlayerEnterFight : "onPlayerEnterFight",
  S2C_PlayerDead : "onPlayerDead",
  S2C_PlayerRevive : "onPlayerRevive",
  S2C_PlayerMove : "onPlayerMove",
  S2C_FightTimeTick : "onFightTimeTick",
  S2C_PlayerKDA : "onPlayerKDA",
  S2C_BattleEnd : "onBattleEnd",
  S2C_PlayerRot : "onPlayerRot",
  S2C_PlayerWeaponRot : "onPlayerWeapnRot",
  S2C_UpdateScores : "onUpdateScores",
  S2C_UpdateGoods : "onUpdateGoods",
  S2C_ResetDailyData : "onResetDailyData",
  S2C_ResetMonthlyData : "onResetMonthlyData",
}